### PR TITLE
Readme modified

### PR DESCRIPTION
**Pull request by kezacardine**

### CODE REVIEW

**Comment by kezacardine** [comment]
I've added the Attendance Management System with necessary tables and a stored procedure.

**Comment by Roman-45** [comment]
This was amazing guys let do it one more time.

**Comment by Samillah47** [comment]
The sample data is well organized. ready to merge!

**Comment by Jean-Luc-of-God** [comment]
For sure, Kudos to all who helped us get insight to this topic!

**Comment by fabricerukundo** [comment]
Why I'm still receive your email?

**Comment by 26878** [comment]
We gained a deeper understanding about this topic. Thx

**Comment by fabricerukundo** [comment]
Guys We did a great work
Best wishes to you all

**Comment by Nzamwitafab** [comment]
I want to extend my gratitude to you for your collaboration on this project. It was truly an amazing experience, and the execution of this process was especially impressive and engaging. Thank you!

**Comment by shemaimable** [comment]
Good job guys🎉

**Comment by ericmaniraguha** [comment]
Goo job but i notice that **AbdourahamaneAdoumGadam** has not participated!

**Comment by mugisha19** [comment]
we did a great work guyz👏🏿

**Comment by AbdourahamaneAdoumGadam** [comment]
I have participated Sir

**Pull request merged**
